apiVersion: v1
kind: Service
metadata:
  name: hu-frontend
  namespace: hu-observability
  labels:
    app.kubernetes.io/name: hu-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: hu-observability
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: hu-frontend
  ports:
    - name: http
      port: 80
      targetPort: http

